# TCL File Generated by Component Editor 18.1
# Mon Jan 02 18:30:36 CET 2023
# DO NOT MODIFY


# 
# checksum_generate "Checksum Generation" v1.0
# Arion 2023.01.02.18:30:36
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module checksum_generate
# 
set_module_property DESCRIPTION ""
set_module_property NAME checksum_generate
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR Arion
set_module_property DISPLAY_NAME "Checksum Generation"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL checksum
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file checksum.vhd VHDL PATH hdl/checksum.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point generation
# 
add_interface generation conduit end
set_interface_property generation associatedClock ""
set_interface_property generation associatedReset ""
set_interface_property generation ENABLED true
set_interface_property generation EXPORT_OF ""
set_interface_property generation PORT_NAME_MAP ""
set_interface_property generation CMSIS_SVD_VARIABLES ""
set_interface_property generation SVD_ADDRESS_GROUP ""

add_interface_port generation decoded input Input 32
add_interface_port generation encoded output Output 32

