# TCL File Generated by Component Editor 18.1
# Mon Jan 02 22:14:49 CET 2023
# DO NOT MODIFY


# 
# vga_controller "VGA Controller" v1.0
# Arion 2023.01.02.22:14:49
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR Arion
set_module_property DISPLAY_NAME "VGA Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file vga_clkgen.vhd VHDL PATH hdl/vga_clkgen.vhd
add_fileset_file vga_interface.vhd VHDL PATH hdl/vga_interface.vhd TOP_LEVEL_FILE
add_fileset_file vga_fsm.vhd VHDL PATH hdl/vga_fsm.vhd
add_fileset_file vga_core.vhd VHDL PATH hdl/vga_core.vhd


# 
# parameters
# 
add_parameter INIT_HBP INTEGER 48
set_parameter_property INIT_HBP DEFAULT_VALUE 48
set_parameter_property INIT_HBP DISPLAY_NAME INIT_HBP
set_parameter_property INIT_HBP TYPE INTEGER
set_parameter_property INIT_HBP UNITS None
set_parameter_property INIT_HBP ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INIT_HBP HDL_PARAMETER true
add_parameter INIT_HFP INTEGER 16
set_parameter_property INIT_HFP DEFAULT_VALUE 16
set_parameter_property INIT_HFP DISPLAY_NAME INIT_HFP
set_parameter_property INIT_HFP TYPE INTEGER
set_parameter_property INIT_HFP UNITS None
set_parameter_property INIT_HFP ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INIT_HFP HDL_PARAMETER true
add_parameter INIT_VBP INTEGER 33
set_parameter_property INIT_VBP DEFAULT_VALUE 33
set_parameter_property INIT_VBP DISPLAY_NAME INIT_VBP
set_parameter_property INIT_VBP TYPE INTEGER
set_parameter_property INIT_VBP UNITS None
set_parameter_property INIT_VBP ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INIT_VBP HDL_PARAMETER true
add_parameter INIT_VFP INTEGER 10
set_parameter_property INIT_VFP DEFAULT_VALUE 10
set_parameter_property INIT_VFP DISPLAY_NAME INIT_VFP
set_parameter_property INIT_VFP TYPE INTEGER
set_parameter_property INIT_VFP UNITS None
set_parameter_property INIT_VFP ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INIT_VFP HDL_PARAMETER true
add_parameter INIT_HDATA INTEGER 640
set_parameter_property INIT_HDATA DEFAULT_VALUE 640
set_parameter_property INIT_HDATA DISPLAY_NAME INIT_HDATA
set_parameter_property INIT_HDATA TYPE INTEGER
set_parameter_property INIT_HDATA UNITS None
set_parameter_property INIT_HDATA ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INIT_HDATA HDL_PARAMETER true
add_parameter INIT_VDATA INTEGER 480
set_parameter_property INIT_VDATA DEFAULT_VALUE 480
set_parameter_property INIT_VDATA DISPLAY_NAME INIT_VDATA
set_parameter_property INIT_VDATA TYPE INTEGER
set_parameter_property INIT_VDATA UNITS None
set_parameter_property INIT_VDATA ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INIT_VDATA HDL_PARAMETER true
add_parameter INIT_HSYNC INTEGER 96
set_parameter_property INIT_HSYNC DEFAULT_VALUE 96
set_parameter_property INIT_HSYNC DISPLAY_NAME INIT_HSYNC
set_parameter_property INIT_HSYNC TYPE INTEGER
set_parameter_property INIT_HSYNC UNITS None
set_parameter_property INIT_HSYNC ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INIT_HSYNC HDL_PARAMETER true
add_parameter INIT_VSYNC INTEGER 2
set_parameter_property INIT_VSYNC DEFAULT_VALUE 2
set_parameter_property INIT_VSYNC DISPLAY_NAME INIT_VSYNC
set_parameter_property INIT_VSYNC TYPE INTEGER
set_parameter_property INIT_VSYNC UNITS None
set_parameter_property INIT_VSYNC ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INIT_VSYNC HDL_PARAMETER true


# 
# display items
# 


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clk
set_interface_property slave associatedReset rst
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave s_address address Input 4
add_interface_port slave s_byteenable byteenable Input 4
add_interface_port slave s_chipselect chipselect Input 1
add_interface_port slave s_read read Input 1
add_interface_port slave s_readdata readdata Output 32
add_interface_port slave s_write write Input 1
add_interface_port slave s_writedata writedata Input 32
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point fifo_control
# 
add_interface fifo_control conduit end
set_interface_property fifo_control associatedClock clk
set_interface_property fifo_control associatedReset ""
set_interface_property fifo_control ENABLED true
set_interface_property fifo_control EXPORT_OF ""
set_interface_property fifo_control PORT_NAME_MAP ""
set_interface_property fifo_control CMSIS_SVD_VARIABLES ""
set_interface_property fifo_control SVD_ADDRESS_GROUP ""

add_interface_port fifo_control o_fifo_baseaddr baseaddr Output 32
add_interface_port fifo_control o_fifo_length length Output 32
add_interface_port fifo_control o_fifo_reset reset Output 1
add_interface_port fifo_control i_fifo_wait wait Input 1
add_interface_port fifo_control i_fifo_debug debug Input 32
add_interface_port fifo_control o_fifo_req req Output 1
add_interface_port fifo_control i_fifo_next next Input 32


# 
# connection point validation
# 
add_interface validation conduit end
set_interface_property validation associatedClock ""
set_interface_property validation associatedReset ""
set_interface_property validation ENABLED true
set_interface_property validation EXPORT_OF ""
set_interface_property validation PORT_NAME_MAP ""
set_interface_property validation CMSIS_SVD_VARIABLES ""
set_interface_property validation SVD_ADDRESS_GROUP ""

add_interface_port validation o_data_test data Output 32
add_interface_port validation i_data_valid valid Input 1

